#include <peekpoke.h>

#define GRAPHICS_CHARACTER_RAM		0x0200L
#define GRAPHICS_SCREEN_RAM		0x0600L

void main() {
	POKE(GRAPHICS_SCREEN_RAM, 0);
	POKE(GRAPHICS_SCREEN_RAM + 1, 1);
	if (PEEK(GRAPHICS_SCREEN_RAM + 1) > 1) {
		POKE(GRAPHICS_SCREEN_RAM + 1, 5);
	}
	else POKE(GRAPHICS_SCREEN_RAM + 2, 2);
}
